import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

// Obsidian's own installer -- and every standard release download -- only
// ever fetches main.js/manifest.json/styles.css, never resources/. This
// embeds each resource file's content into a TS module that main.ts
// imports, so it can write them out itself on load (see
// hooks/provisionResources.ts) regardless of how the plugin was installed.
// Run before tsc (not just inside esbuild.config.mjs, which runs *after*
// tsc in the build script) so `import ... from "../generated/resourceFiles"`
// resolves even on a fresh checkout -- see package.json's pretsc/predev hooks.
const EMBEDDED_RESOURCE_FILES = [
  { relativePath: "pty_helper.py", executable: true },
  { relativePath: "hook-bridge.sh", executable: true },
  { relativePath: "shell-integration/zsh/.zshenv", executable: false },
  { relativePath: "shell-integration/bash/.bash_profile", executable: false },
];

export function generateResourceFilesModule() {
  const entries = EMBEDDED_RESOURCE_FILES.map(({ relativePath, executable }) => {
    const content = readFileSync(`resources/${relativePath}`, "utf8");
    return `  { relativePath: ${JSON.stringify(relativePath)}, content: ${JSON.stringify(content)}, executable: ${executable} },`;
  });
  const source = `// GENERATED by scripts/generateResourceFiles.mjs from resources/* -- do not edit directly.
export interface ResourceFile {
  relativePath: string;
  content: string;
  executable: boolean;
}

export const RESOURCE_FILES: ResourceFile[] = [
${entries.join("\n")}
];
`;
  mkdirSync("src/generated", { recursive: true });
  writeFileSync("src/generated/resourceFiles.ts", source);
}

// Executed directly (as an npm pre-hook), not just imported.
if (import.meta.url === `file://${process.argv[1]}`) {
  generateResourceFilesModule();
}
